export const quotes: string[] = [
    '"Talk is cheap. Show me the code."',
    '"There are two ways to write error-free programs; only the third one works."',
    '"Programmers are tools for converting caffeine into code."',
    '"Code is like humor. When you have to explain it, it’s bad."',
    '"Software is like entropy: It is difficult to grasp, weighs nothing, and obeys the second law of thermodynamics; i.e., it always increases."',
    '"The best way to predict the future is to invent it."',
    '"It’s not a bug; it’s an undocumented feature."',
    '"If debugging is the process of removing software bugs, then programming must be the process of putting them in."',
    '"Any fool can write code that a computer can understand. Good programmers write code that humans can understand."',
    '"Weeks of programming can save you hours of planning."',
    '"Before software can be reusable it first has to be usable."',
    '"Simplicity is the soul of efficiency."',
    '"Make it work, make it right, make it fast."',
    '"Deleted code is debugged code."',
    '"There is no place like 127.0.0.1."',
    '"Programming isn\'t about what you know; it\'s about what you can figure out."',
    '"The most dangerous phrase in software development: ‘We’ve always done it this way.’"',
    '"Why do we never have time to do it right, but always have time to do it over?"',
    '"One man’s crappy software is another man’s full-time job."',
    '"Java is to JavaScript what car is to carpet."',
    '"Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday’s code."',
    '"Optimism is an occupational hazard of programming; feedback is the treatment."',
    '"If at first you don’t succeed, call it version 1.0."',
    '"A language that doesn’t affect the way you think about programming is not worth knowing."',
    '"Code never lies, comments sometimes do."',
    '"Computers are good at following instructions, but not at reading your mind."',
    '"Premature optimization is the root of all evil."',
    '"Any sufficiently advanced technology is indistinguishable from magic."',
    '"There are 10 types of people in the world: those who understand binary and those who don’t."',
    '"Don’t worry if it doesn’t work right. If everything did, you’d be out of a job."',
    '"First, solve the problem. Then, write the code."',
    '"The best error message is the one that never shows up."',
    '"If it works, don’t touch it."',
    '"Measuring programming progress by lines of code is like measuring aircraft building progress by weight."',
    '"The quieter you are, the more you can hear."',
    '"Debugging is like being the detective in a crime movie where you are also the murderer."',
    '"Programs must be written for people to read, and only incidentally for machines to execute."',
    '"There’s no test like production."',
    '"A good programmer is someone who always looks both ways before crossing a one-way street."',
    '"Every great developer you know got there by solving problems they were unqualified to solve until they actually did it."',
    '"Software developers like to solve problems. If there are no problems available, they will create their own problems."',
    '"Computers are incredibly fast, accurate, and stupid. Humans are incredibly slow, inaccurate, and brilliant. Together they are powerful beyond imagination."',
    '"Good code is its own best documentation."',
    '"In programming, the hard part isn’t solving problems, but deciding what problems to solve."',
    '"When in doubt, use brute force."',
    '"You can’t have great software without a great team, and most software teams behave like dysfunctional families."',
    '"The best thing about a boolean is even if you are wrong, you are only off by a bit."',
    '"Some people, when confronted with a problem, think, \'I know, I’ll use regular expressions.\' Now they have two problems."',
    '"Programming is the art of algorithm design and the craft of debugging errant code."',
    '"Software testing is a sport like hunting, it\'s bug hunting."',
    '"A program is never less than 90% complete, and never more than 95%."',
    '"In theory, theory and practice are the same. In practice, they’re not."',
    '"Programs are meant to be read by humans and only incidentally for computers to execute."',
    '"Real programmers count from 0."',
    '"Don’t repeat yourself (DRY)."',
    '"Code simplicity matters."',
    '"Less code, less bugs."',
    '"Smart data structures and dumb code works a lot better than the other way around."',
    '"Refactoring is like cleaning up after cooking."',
    '"If you automate a mess, you get an automated mess."'
  ];